services:
  admin.user:
    class: Galvesband\TraUserBundle\Admin\UserAdmin
    arguments: [~, Galvesband\TraUserBundle\Entity\User, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: User }

  admin.group:
    class: Galvesband\TraUserBundle\Admin\GroupAdmin
    arguments: [~, Galvesband\TraUserBundle\Entity\Group, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Group }

  admin.role:
    class: Galvesband\TraUserBundle\Admin\RoleAdmin
    arguments: [~, Galvesband\TraUserBundle\Entity\Role, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Role }

  tra_user.manager:
    class: Galvesband\TraUserBundle\DependencyInjection\UserManager
    arguments:
      - "@security.encoder_factory"
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }

#    galvesband_tra_user.example:
#        class: Galvesband\TraUserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
