<?php

/*
 * This file is part of the Galvesband TraUserBundle.
 *
 * (c) Rafael Gálvez-Cañero
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Galvesband\TraUserBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    /**
     * @param string $name
     * @return \Galvesband\TraUserBundle\Entity\Group
     */
    public function findByName($name) {
        $group = $this->createQueryBuilder('g')
            ->where('g.name = :group_name')
            ->setParameter('group_name', $name)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();

        return $group;
    }
}
