<?php

namespace Galvesband\TraUserBundle\Entity;

/**
 * ResetTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResetTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
