<?php

/*
 * This file is part of the Galvesband TraUserBundle.
 *
 * (c) Rafael Gálvez-Cañero
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Galvesband\TraUserBundle\Entity;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name
     * @return Role
     */
    public function findByName($name)
    {
        $role = $this->createQueryBuilder('r')
            ->where('r.name = :role_name')
            ->setParameter('role_name', $name)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();

        return $role;
    }
}
